#!/bin/bash
# Will start three elevators on three different simulators

# Start three simulators
gnome-terminal --geometry=80x20+1000+760 -e 'Simulator-v2/SimElevatorServer --port=14558'

# Start three nodes
gnome-terminal --geometry=80x20+250+760 -e 'go run main.go -id=4 -port=14558'